<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::insert(array(
            array("id" => "1","name" => "AFGHANISTAN","slug"=> "afghanistan","continent"=>"Africa"),
            array('id' => '2','name' => "ALBANIA",'slug'=> "albania","continent"=>"Europe"),
            array('id' => '3','name' => "ALGERIA",'slug'=> "algeria","continent"=>"Africa"),
            array('id' => '4','name' => "AMERICAN SAMOA",'slug'=> "american-samoa","continent"=>"Oceania"),
            array('id' => '5','name' => "ANGOLA",'slug'=> "angola","continent"=>"Africa"),
            array('id' => '6','name' => "ANGUILLA",'slug'=> "anguilla","continent"=>"North America"),
            array('id' => '7','name' => "ANTARCTICA",'slug'=> "antarctica","continent"=>"Antarctica"),
            array('id' => '8','name' => "ANTIGUA AND BARBUDA",'slug'=> "antigua-and-barbuda","North America"),
            array('id' => '9','name' => "ARGENTINA",'slug'=> "argentina","continent"=> "South America"),
            array('id' => '10','name' => "ARMENIA",'slug'=> "armenia","continent"=>"Asia"),
            array('id' => '11','name' => "ARUBA",'slug'=> "aruba","continent" => "South America"),
            array('id' => '12','name' => "AUSTRALIA",'slug'=> "australia","continent"=>"Australia"),
            array('id' => '13','name' => "AUSTRIA",'slug'=> "austria","continent"=>"Europe"),
            array('id' => '14', 'name' => 'AZERBAIJAN', 'slug' => 'azerbaijan', 'continent' => 'Asia'),
            array('id' => '15', 'name' => 'BAHAMAS', 'slug' => 'bahamas', 'continent' => 'North America'),
            array('id' => '16', 'name' => 'BAHRAIN', 'slug' => 'bahrain', 'continent' => 'Asia'),
            array('id' => '17', 'name' => 'BANGLADESH', 'slug' => 'bangladesh', 'continent' => 'Asia'),
            array('id' => '18', 'name' => 'BARBADOS', 'slug' => 'barbados', 'continent' => 'North America'),
            array('id' => '19', 'name' => 'BELARUS', 'slug' => 'belarus', 'continent' => 'Europe'),
            array('id' => '20', 'name' => 'BELGIUM', 'slug' => 'belgium', 'continent' => 'Europe'),
            array('id' => '21', 'name' => 'BELIZE', 'slug' => 'belize', 'continent' => 'North America'),
            array('id' => '22', 'name' => 'BENIN', 'slug' => 'benin', 'continent' => 'Africa'),
            array('id' => '23', 'name' => 'BERMUDA', 'slug' => 'bermuda', 'continent' => 'North America'),
            array('id' => '24', 'name' => 'BHUTAN', 'slug' => 'bhutan', 'continent' => 'Asia'),
            array('id' => '25', 'name' => 'BOLIVIA', 'slug' => 'bolivia', 'continent' => 'South America'),
            array('id' => '26', 'name' => 'BOSNIA AND HERZEGOVINA', 'slug' => 'bosnia-and-herzegowina', 'continent' => 'Europe'),
            array('id' => '27', 'name' => 'BOTSWANA', 'slug' => 'botswana', 'continent' => 'Africa'),
            array('id' => '28', 'name' => 'BRAZIL', 'slug' => 'brazil', 'continent' => 'South America'),
            array('id' => '29', 'name' => 'BRUNEI DARUSSALAM', 'slug' => 'brunei-darussalam', 'continent' => 'Asia'),
            array('id' => '30', 'name' => 'BULGARIA', 'slug' => 'bulgaria', 'continent' => 'Europe'),
            array('id' => '31', 'name' => 'BURKINA FASO', 'slug' => 'burkina-faso', 'continent' => 'Africa'),
            array('id' => '32', 'name' => 'BURUNDI', 'slug' => 'burundi', 'continent' => 'Africa'),
            array('id' => '33', 'name' => 'CAMBODIA', 'slug' => 'cambodia', 'continent' => 'Asia'),
            array('id' => '34', 'name' => 'CAMEROON', 'slug' => 'cameroon', 'continent' => 'Africa'),
            array('id' => '35', 'name' => 'CANADA', 'slug' => 'canada', 'continent' => 'North America'),
            array('id' => '36', 'name' => 'CAPE VERDE', 'slug' => 'cape-verde', 'continent' => 'Africa'),
            array('id' => '37', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'slug' => 'central-african-republic', 'continent' => 'Africa'),
            array('id' => '38', 'name' => 'CHAD', 'slug' => 'chad', 'continent' => 'Africa'),
            array('id' => '39', 'name' => 'CHILE', 'slug' => 'chile', 'continent' => 'South America'),
            array('id' => '40', 'name' => 'CHINA', 'slug' => 'china', 'continent' => 'Asia'),
            array('id' => '41', 'name' => 'COLOMBIA', 'slug' => 'colombia', 'continent' => 'South America'),
            array('id' => '42', 'name' => 'COMOROS', 'slug' => 'comoros', 'continent' => 'Africa'),
            array('id' => '43', 'name' => 'CONGO', 'slug' => 'congo', 'continent' => 'Africa'),
            array('id' => '44', 'name' => 'CONGO, THE DRC', 'slug' => 'congo-the-drc', 'continent' => 'Africa'),
            array('id' => '45', 'name' => 'COSTA RICA', 'slug' => 'costa-rica', 'continent' => 'North America'),
            array('id' => '46', 'name' => 'COTE D`IVOIRE', 'slug' => 'cote-divoire', 'continent' => 'Africa'),
            array('id' => '47', 'name' => 'CROATIA', 'slug' => 'croatia-', 'continent' => 'Europe'),
            array('id' => '48', 'name' => 'CUBA', 'slug' => 'cuba', 'continent' => 'North America'),
            array('id' => '49', 'name' => 'CYPRUS', 'slug' => 'cyprus', 'continent' => 'Europe'),
            array('id' => '50', 'name' => 'CZECH REPUBLIC', 'slug' => 'czech-republic', 'continent' => 'Europe'),
            array('id' => '51', 'name' => 'DENMARK', 'slug' => 'denmark', 'continent' => 'Europe'),
            array('id' => '52', 'name' => 'DJIBOUTI', 'slug' => 'djibouti', 'continent' => 'Africa'),
            array('id' => '53', 'name' => 'DOMINICA', 'slug' => 'dominica', 'continent' => 'North America'),
            array('id' => '54', 'name' => 'DOMINICAN REPUBLIC', 'slug' => 'dominican-republic', 'continent' => 'North America'),
            array('id' => '55', 'name' => 'EAST TIMOR', 'slug' => 'east-timor', 'continent' => 'Asia'),
            array('id' => '56', 'name' => 'ECUADOR', 'slug' => 'ecuador', 'continent' => 'South America'),
            array('id' => '57', 'name' => 'EGYPT', 'slug' => 'egypt', 'continent' => 'Africa'),
            array('id' => '58', 'name' => 'EL SALVADOR', 'slug' => 'el-salvador', 'continent' => 'North America'),
            array('id' => '59', 'name' => 'EQUATORIAL GUINEA', 'slug' => 'equatorial-guinea', 'continent' => 'Africa'),
            array('id' => '60', 'name' => 'ERITREA', 'slug' => 'eritrea', 'continent' => 'Africa'),
            array('id' => '61', 'name' => 'ESTONIA', 'slug' => 'estonia', 'continent' => 'Europe'),
            array('id' => '62', 'name' => 'ETHIOPIA', 'slug' => 'ethiopia', 'continent' => 'Africa'),
            array('id' => '63', 'name' => 'FIJI', 'slug' => 'fiji', 'continent' => 'Oceania'),
            array('id' => '64', 'name' => 'FINLAND', 'slug' => 'finland', 'continent' => 'Europe'),
            array('id' => '65', 'name' => 'FRANCE', 'slug' => 'france', 'continent' => 'Europe'),
            array('id' => '66', 'name' => 'FRANCE, METROPOLITAN', 'slug' => 'france-metropolitan', 'continent' => 'Europe'),
            array('id' => '67', 'name' => 'FRENCH GUIANA', 'slug' => 'french-guiana', 'continent' => 'South America'),
            array('id' => '68', 'name' => 'GABON', 'slug' => 'gabon', 'continent' => 'Africa'),
            array('id' => '69', 'name' => 'GAMBIA', 'slug' => 'gambia', 'continent' => 'Africa'),
            array('id' => '70', 'name' => 'GEORGIA', 'slug' => 'georgia', 'continent' => 'Asia'),
            array('id' => '71', 'name' => 'GERMANY', 'slug' => 'germany', 'continent' => 'Europe'),
            array('id' => '72', 'name' => 'GHANA', 'slug' => 'ghana', 'continent' => 'Africa'),
            array('id' => '73', 'name' => 'GREECE', 'slug' => 'greece', 'continent' => 'Europe'),
            array('id' => '74', 'name' => 'GREENLAND', 'slug' => 'greenland', 'continent' => 'North America'),
            array('id' => '75', 'name' => 'GRENADA', 'slug' => 'grenada', 'continent' => 'North America'),
            array('id' => '76', 'name' => 'GUADELOUPE', 'slug' => 'guadeloupe', 'continent' => 'North America'),
            array('id' => '77', 'name' => 'GUATEMALA', 'slug' => 'guatemala', 'continent' => 'North America'),
            array('id' => '78', 'name' => 'GUINEA', 'slug' => 'guinea', 'continent' => 'Africa'),
            array('id' => '79', 'name' => 'BISSAU', 'slug' => 'bissau', 'continent' => 'Africa'),
            array('id' => '80', 'name' => 'GUYANA', 'slug' => 'guyana', 'continent' => 'South America'),
            array('id' => '81', 'name' => 'HAITI', 'slug' => 'haiti', 'continent' => 'North America'),
            array('id' => '82', 'name' => 'HOLY SEE', 'slug' => 'holy-see', 'continent' => 'Europe'),
            array('id' => '83', 'name' => 'HONDURAS', 'slug' => 'honduras', 'continent' => 'North America'),
            array('id' => '84', 'name' => 'HONG KONG', 'slug' => 'hong-kong', 'continent' => 'Asia'),
            array('id' => '85', 'name' => 'HUNGARY', 'slug' => 'hungary', 'continent' => 'Europe'),
            array('id' => '86', 'name' => 'ICELAND', 'slug' => 'iceland', 'continent' => 'Europe'),
            array('id' => '87', 'name' => 'INDONESIA', 'slug' => 'indonesia', 'continent' => 'Asia'),
            array('id' => '88', 'name' => 'IRAN', 'slug' => 'iran', 'continent' => 'Asia'),
            array('id' => '89', 'name' => 'IRAQ', 'slug' => 'iraq', 'continent' => 'Asia'),
            array('id' => '90', 'name' => 'IRELAND', 'slug' => 'ireland', 'continent' => 'Europe'),
            array('id' => '91', 'name' => 'ISRAEL', 'slug' => 'israel', 'continent' => 'Asia'),
            array('id' => '92', 'name' => 'ITALY', 'slug' => 'italy', 'continent' => 'Europe'),
            array('id' => '93', 'name' => 'JAMAICA', 'slug' => 'jamaica', 'continent' => 'North America'),
            array('id' => '94', 'name' => 'JAPAN', 'slug' => 'japan', 'continent' => 'Asia'),
            array('id' => '95', 'name' => 'JORDAN', 'slug' => 'jordan', 'continent' => 'Asia'),
            array('id' => '96', 'name' => 'KAZAKHSTAN', 'slug' => 'kazakhstan', 'continent' => 'Asia'),
            array('id' => '97', 'name' => 'KENYA', 'slug' => 'kenya', 'continent' => 'Africa'),
            array('id' => '98', 'name' => 'KIRIBATI', 'slug' => 'kiribati', 'continent' => 'Oceania'),
            array('id' => '99', 'name' => 'KOREA, D.P.R.O.', 'slug' => 'korea', 'continent' => 'Asia'),
            array('id' => '100', 'name' => 'KUWAIT', 'slug' => 'kuwait', 'continent' => 'Asia'),
            array('id' => '101', 'name' => 'KYRGYZSTAN', 'slug' => 'kyrgyzstan', 'continent' => 'Asia'),
            array('id' => '102', 'name' => 'LAOS', 'slug' => 'laos', 'continent' => 'Asia'),
            array('id' => '103', 'name' => 'LATVIA', 'slug' => 'latvia', 'continent' => 'Europe'),
            array('id' => '104', 'name' => 'LEBANON', 'slug' => 'lebanon', 'continent' => 'Asia'),
            array('id' => '105', 'name' => 'LESOTHO', 'slug' => 'lesotho', 'continent' => 'Africa'),
            array('id' => '106', 'name' => 'LIBERIA', 'slug' => 'liberia', 'continent' => 'Africa'),
            array('id' => '107', 'name' => 'LIECHTENSTEIN', 'slug' => 'liechtenstein', 'continent' => 'Europe'),
            array('id' => '108', 'name' => 'LITHUANIA', 'slug' => 'lithuania', 'continent' => 'Europe'),
            array('id' => '109', 'name' => 'LUXEMBOURG', 'slug' => 'luxembourg', 'continent' => 'Europe'),
            array('id' => '110', 'name' => 'MACAU', 'slug' => 'macau', 'continent' => 'Asia'),
            array('id' => '111', 'name' => 'MACEDONIA', 'slug' => 'macedonia', 'continent' => 'Europe'),
            array('id' => '112', 'name' => 'MADAGASCAR', 'slug' => 'madagascar', 'continent' => 'Africa'),
            array('id' => '113', 'name' => 'MALAWI', 'slug' => 'malawi', 'continent' => 'Africa'),
            array('id' => '114', 'name' => 'MALAYSIA', 'slug' => 'malaysia', 'continent' => 'Asia'),
            array('id' => '115', 'name' => 'MALDIVES', 'slug' => 'maldives', 'continent' => 'Asia'),
            array('id' => '116', 'name' => 'MALI', 'slug' => 'mali', 'continent' => 'Africa'),
            array('id' => '117', 'name' => 'MALTA', 'slug' => 'malta', 'continent' => 'Europe'),
            array('id' => '118', 'name' => 'MARSHALL ISLANDS', 'slug' => 'marshall-islands', 'continent' => 'Oceania'),
            array('id' => '119', 'name' => 'MAURITANIA', 'slug' => 'mauritania', 'continent' => 'Africa'),
            array('id' => '120', 'name' => 'MAURITIUS', 'slug' => 'mauritius', 'continent' => 'Africa'),
            array('id' => '121', 'name' => 'MEXICO', 'slug' => 'mexico', 'continent' => 'North America'),
            array('id' => '122', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'slug' => 'micronesia-federated-states-of', 'continent' => 'Oceania'),
            array('id' => '123', 'name' => 'MOLDOVA, REPUBLIC OF', 'slug' => 'moldova-republic-of', 'continent' => 'Europe'),
            array('id' => '124', 'name' => 'MONACO', 'slug' => 'monaco', 'continent' => 'Europe'),
            array('id' => '125', 'name' => 'MONGOLIA', 'slug' => 'mongolia', 'continent' => 'Asia'),
            array('id' => '126', 'name' => 'MONTENEGRO', 'slug' => 'montenegro', 'continent' => 'Europe'),
            array('id' => '127', 'name' => 'MOROCCO', 'slug' => 'morocco', 'continent' => 'Africa'),
            array('id' => '128', 'name' => 'MOZAMBIQUE', 'slug' => 'mozambique', 'continent' => 'Africa'),
            array('id' => '129', 'name' => 'MYANMAR (BURMA)', 'slug' => 'myanmar', 'continent' => 'Asia'),
            array('id' => '130', 'name' => 'NAMIBIA', 'slug' => 'namibia', 'continent' => 'Africa'),
            array('id' => '131', 'name' => 'NAURU', 'slug' => 'nauru', 'continent' => 'Oceania'),
            array('id' => '132', 'name' => 'NEPAL', 'slug' => 'nepal', 'continent' => 'Asia'),
            array('id' => '133', 'name' => 'NEW ZEALAND', 'slug' => 'new-zealand', 'continent' => 'Oceania'),
            array('id' => '134', 'name' => 'NICARAGUA', 'slug' => 'nicaragua', 'continent' => 'North America'),
            array('id' => '135', 'name' => 'NIGER', 'slug' => 'niger', 'continent' => 'Africa'),
            array('id' => '136', 'name' => 'NIGERIA', 'slug' => 'nigeria', 'continent' => 'Africa'),
            array('id' => '137', 'name' => 'NORWAY', 'slug' => 'norway', 'continent' => 'Europe'),
            array('id' => '138', 'name' => 'OMAN', 'slug' => 'oman', 'continent' => 'Asia'),
            array('id' => '139', 'name' => 'PAKISTAN', 'slug' => 'pakistan', 'continent' => 'Asia'),
            array('id' => '140', 'name' => 'PALAU', 'slug' => 'palau', 'continent' => 'Oceania'),
            array('id' => '141', 'name' => 'PANAMA', 'slug' => 'panama', 'continent' => 'North America'),
            array('id' => '142', 'name' => 'PAPUA NEW GUINEA', 'slug' => 'papua-new-guinea', 'continent' => 'Oceania'),
            array('id' => '143', 'name' => 'PARAGUAY', 'slug' => 'paraguay', 'continent' => 'South America'),
            array('id' => '144', 'name' => 'PERU', 'slug' => 'peru', 'continent' => 'South America'),
            array('id' => '145', 'name' => 'PHILIPPINES', 'slug' => 'philippines', 'continent' => 'Asia'),
            array('id' => '146', 'name' => 'POLAND', 'slug' => 'poland', 'continent' => 'Europe'),
            array('id' => '149', 'name' => 'PORTUGAL', 'slug' => 'portugal', 'continent' => 'Europe'),
            array('id' => '150', 'name' => 'PUERTO RICO', 'slug' => 'puerto-rico', 'continent' => 'North America'),
            array('id' => '151', 'name' => 'QATAR', 'slug' => 'qatar', 'continent' => 'Asia'),
    array('id' => '152', 'name' => 'ROMANIA', 'slug' => 'romania', 'continent' => 'Europe'),
    array('id' => '153', 'name' => 'RUSSIAN FEDERATION', 'slug' => 'russian-federation', 'continent' => 'Europe'),
    array('id' => '154', 'name' => 'RWANDA', 'slug' => 'rwanda', 'continent' => 'Africa'),
    array('id' => '155', 'name' => 'SAINT KITTS AND NEVIS', 'slug' => 'saint-kitts-and-nevis', 'continent' => 'North America'),
    array('id' => '156', 'name' => 'SAINT LUCIA', 'slug' => 'saint-lucia', 'continent' => 'North America'),
    array('id' => '157', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'slug' => 'saint-vincent-and-the-grenadines', 'continent' => 'North America'),
    array('id' => '158', 'name' => 'SAMOA', 'slug' => 'samoa', 'continent' => 'Oceania'),
    array('id' => '159', 'name' => 'SAN MARINO', 'slug' => 'san-marino', 'continent' => 'Europe'),
    array('id' => '160', 'name' => 'SAO TOME AND PRINCIPE', 'slug' => 'sao-tome-and-principe', 'continent' => 'Africa'),
    array('id' => '161', 'name' => 'SAUDI ARABIA', 'slug' => 'saudi-arabia', 'continent' => 'Asia'),
    array('id' => '162', 'name' => 'SENEGAL', 'slug' => 'senegal', 'continent' => 'Africa'),
    array('id' => '163', 'name' => 'SERBIA', 'slug' => 'serbia', 'continent' => 'Europe'),
    array('id' => '164', 'name' => 'SEYCHELLES', 'slug' => 'seychelles', 'continent' => 'Africa'),
    array('id' => '165', 'name' => 'SIERRA LEONE', 'slug' => 'sierra-leone', 'continent' => 'Africa'),
    array('id' => '166', 'name' => 'SINGAPORE', 'slug' => 'singapore', 'continent' => 'Asia'),
    array('id' => '167', 'name' => 'SLOVAKIA (SLOVAK REPUBLIC)', 'slug' => 'slovakia', 'continent' => 'Europe'),
    array('id' => '168', 'name' => 'SLOVENIA', 'slug' => 'slovenia', 'continent' => 'Europe'),
    array('id' => '169', 'name' => 'SOLOMON ISLANDS', 'slug' => 'solomon-islands', 'continent' => 'Oceania'),
    array('id' => '170', 'name' => 'SOMALIA', 'slug' => 'somalia', 'continent' => 'Africa'),
    array('id' => '171', 'name' => 'SOUTH AFRICA', 'slug' => 'south-africa', 'continent' => 'Africa'),
    array('id' => '172', 'name' => 'SOUTH GEORGIA AND SOUTH S.S', 'slug' => 'south-georgia-and-south-s.s', 'continent' => 'Antarctica'),
    array('id' => '173', 'name' => 'SOUTH KOREA', 'slug' => 'south-korea', 'continent' => 'Asia'),
    array('id' => '174', 'name' => 'SOUTH SUDAN', 'slug' => 'south-sudan', 'continent' => 'Africa'),
    array('id' => '175', 'name' => 'SPAIN', 'slug' => 'spain', 'continent' => 'Europe'),
    array('id' => '176', 'name' => 'SRI LANKA', 'slug' => 'sri-lanka', 'continent' => 'Asia'),
    array('id' => '177', 'name' => 'SUDAN', 'slug' => 'sudan', 'continent' => 'Africa'),
    array('id' => '178', 'name' => 'SURINAME', 'slug' => 'suriname', 'continent' => 'South America'),
    array('id' => '179', 'name' => 'SWEDEN', 'slug' => 'sweden', 'continent' => 'Europe'),
    array('id' => '180', 'name' => 'SWITZERLAND', 'slug' => 'switzerland', 'continent' => 'Europe'),
    array('id' => '181', 'name' => 'SYRIAN ARAB REPUBLIC', 'slug' => 'syrian-arab-republic', 'continent' => 'Asia'),
    array('id' => '182', 'name' => 'TAIWAN, PROVINCE OF CHINA', 'slug' => 'taiwan-province-of-china', 'continent' => 'Asia'),
    array('id' => '183', 'name' => 'TAJIKISTAN', 'slug' => 'tajikistan', 'continent' => 'Asia'),
    array('id' => '184', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'slug' => 'tanzania-united-republic-of', 'continent' => 'Africa'),
    array('id' => '185', 'name' => 'THAILAND', 'slug' => 'thailand', 'continent' => 'Asia'),
    array('id' => '186', 'name' => 'TOGO', 'slug' => 'togo', 'continent' => 'Africa'),
    array('id' => '187', 'name' => 'TONGA', 'slug' => 'tonga', 'continent' => 'Oceania'),
    array('id' => '188', 'name' => 'TRINIDAD AND TOBAGO', 'slug' => 'trinidad-and-tobago', 'continent' => 'North America'),
    array('id' => '189', 'name' => 'TUNISIA', 'slug' => 'tunisia', 'continent' => 'Africa'),
    array('id' => '190', 'name' => 'TURKEY', 'slug' => 'turkey', 'continent' => 'Europe'),
    array('id' => '191', 'name' => 'TURKMENISTAN', 'slug' => 'turkmenistan', 'continent' => 'Asia'),
    array('id' => '192', 'name' => 'UGANDA', 'slug' => 'uganda', 'continent' => 'Africa'),
    array('id' => '193', 'name' => 'UKRAINE', 'slug' => 'ukraine', 'continent' => 'Europe'),
    array('id' => '194', 'name' => 'UNITED ARAB EMIRATES', 'slug' => 'united-arab-emirates', 'continent' => 'Asia'),
    array('id' => '195', 'name' => 'UNITED KINGDOM', 'slug' => 'united-kingdom', 'continent' => 'Europe'),
    array('id' => '196', 'name' => 'UNITED STATES', 'slug' => 'united-states', 'continent' => 'North America'),
    array('id' => '197', 'name' => 'URUGUAY', 'slug' => 'uruguay', 'continent' => 'South America'),
    array('id' => '198', 'name' => 'UZBEKISTAN', 'slug' => 'uzbekistan', 'continent' => 'Asia'),
    array('id' => '199', 'name' => 'VANUATU', 'slug' => 'vanuatu', 'continent' => 'Oceania'),
    array('id' => '200', 'name' => 'VENEZUELA', 'slug' => 'venezuela', 'continent' => 'South America'),
    array('id' => '201', 'name' => 'VIETNAM', 'slug' => 'vietnam', 'continent' => 'Asia'),
    array('id' => '202', 'name' => 'YEMEN', 'slug' => 'yemen', 'continent' => 'Asia'),
    array('id' => '203', 'name' => 'ZAMBIA', 'slug' => 'zambia', 'continent' => 'Africa'),
    array('id' => '204', 'name' => 'ZIMBABWE', 'slug' => 'zimbabwe', 'continent' => 'Africa'),
    array('id' => '205', 'name' => 'SCHENGEN', 'slug' => 'schengen', 'continent' => 'Europe'),
    array('id' => '206', 'name' => 'INDIA VISA (UK CITIZEN)', 'slug' => 'india-visa-(uk-citizen)', 'continent' => 'Asia'),
    array('id' => '207', 'name' => 'INDIA VISA (USA CITIZEN)', 'slug' => 'india-visa-(usa-citizen)', 'continent' => 'Asia'),
        ));  
    }
}